#!/bin/bash
#-------------------------------------------------------
# Bash-script autogenerated by im4java
# at Wed Jun 20 18:49:39 PDT 2012
#-------------------------------------------------------

convert \
  \
  "/Users/angellopozo/Dropbox/My Code/java/MainRabbitMongo/Resources/CreatedPDF_TestMongo_Graded_Vsmaller.pdf[3]"\
  -colorspace "RGB"-type "TrueColor" "jpg:-" 

