#!/bin/bash
#-------------------------------------------------------
# Bash-script autogenerated by im4java
# at Tue Mar 13 17:25:33 PDT 2012
#-------------------------------------------------------

convert \
  "/Users/angellopozo/Documents/TestImages/PDF_CRICLEV2.pdf[1]" \
  -colorspace "RGB"-type "TrueColor" "jpg:-" 

